---
# tasks file for configure_firewall
- name: latest security packages installed
  yum:
    name: "{{ item }}"
    state: latest
  with_items: "{{ security_packages }}"

- name: firewalld enabled and running
  service:
    name: "{{ item }}"
    enabled: true
    state: started
  with_items: "{{ services_to_enable }}"

- name: firewalld permits http service
  firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
    immediate: true
  with_items: "{{ firewall_services }}"

